# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('accesstoken', models.CharField(max_length=255, null=True)),
                ('organization', models.CharField(max_length=255, null=True)),
                ('date', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('count', models.IntegerField(auto_created=True, max_length=11, primary_key=True, serialize=False)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('default_profile', models.CharField(max_length=255, null=True)),
                ('default_profile_image', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('favorites_count', models.CharField(max_length=255, null=True)),
                ('followers_count', models.CharField(max_length=255, null=True)),
                ('friends_count', models.CharField(max_length=255, null=True)),
                ('id', models.CharField(max_length=255, null=True)),
                ('lang', models.CharField(max_length=255, null=True)),
                ('listed_count', models.CharField(max_length=255, null=True)),
                ('location', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('profile_background_image_url', models.TextField(null=True)),
                ('profile_image_url', models.TextField(null=True)),
                ('screen_name', models.TextField(null=True)),
                ('statuses_count', models.CharField(max_length=255, null=True)),
                ('time_zone', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('utc_offset', models.CharField(max_length=255, null=True)),
                ('verified', models.CharField(max_length=255, null=True)),
                ('rank', models.IntegerField(max_length=11, null=True)),
                ('hash', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.CharField(max_length=255, null=True)),
                ('screen_name', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('rank', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.IntegerField(auto_created=True, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('comment', models.TextField(null=True)),
                ('os', models.CharField(max_length=255, null=True)),
                ('pcuser', models.CharField(max_length=255, null=True)),
                ('ip', models.CharField(max_length=255, null=True)),
                ('date', models.CharField(max_length=255, null=True)),
                ('macaddress', models.CharField(max_length=255, null=True)),
                ('hash', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('retweet_count', models.CharField(max_length=255, null=True)),
                ('favorite_count', models.CharField(max_length=255, null=True)),
                ('in_reply_to_user_id', models.CharField(max_length=255, null=True)),
                ('in_reply_to_status_id', models.CharField(max_length=255, null=True)),
                ('text', models.CharField(max_length=255, null=True)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('iso_language_code', models.CharField(max_length=255, null=True)),
                ('source', models.CharField(max_length=255, null=True)),
                ('lang', models.CharField(max_length=255, null=True)),
                ('good', models.IntegerField(max_length=11, null=True)),
                ('bad', models.IntegerField(max_length=11, null=True)),
            ],
        ),
    ]
