# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('count', models.IntegerField(auto_created=True, max_length=11, primary_key=True, serialize=False)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('default_profile', models.CharField(max_length=255, null=True)),
                ('default_profile_image', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('favorites_count', models.CharField(max_length=255, null=True)),
                ('followers_count', models.CharField(max_length=255, null=True)),
                ('friends_count', models.CharField(max_length=255, null=True)),
                ('id', models.CharField(max_length=255, null=True)),
                ('lang', models.CharField(max_length=255, null=True)),
                ('listed_count', models.CharField(max_length=255, null=True)),
                ('location', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('profile_background_image_url', models.TextField(null=True)),
                ('profile_image_url', models.TextField(null=True)),
                ('screen_name', models.TextField(null=True)),
                ('statuses_count', models.CharField(max_length=255, null=True)),
                ('time_zone', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('utc_offset', models.CharField(max_length=255, null=True)),
                ('verified', models.CharField(max_length=255, null=True)),
                ('rank', models.IntegerField(max_length=11, null=True)),
                ('hash', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='AppUser',
            new_name='Infomation',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
