# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight_server', '0003_tweet_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='count',
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='bad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='good',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
